### ISSUE TITLE
Docker compose up/down not working due to misconfigured depends_on at docker-compose.yml

### ISSUE THREAD

**Issue by lindenb1** [numerique-gouv/impress#339]
## Bug Report

**Problematic behavior**
Using docker compose down after the bootstrap and docker compose up to start the project again will lead to the following error:

impress-nginx-1          | 2024/10/15 08:35:13 [emerg] 1#1: host not found in upstream "app-dev" in /etc/nginx/conf.d/default.conf:25
impress-nginx-1          | nginx: [emerg] host not found in upstream "app-dev" in /etc/nginx/conf.d/default.conf:25
impress-nginx-1 exited with code 1

This behavior makes sense as the docker-compose file appears to be configured wrong. At the `app-dev:` section, we have a `depends_on -nginx`, but vise versa nginx cannot work without app-dev ... To resolve this, nginx should get removed from depends_on at app-dev, and instead we should make nginx depend_on app-dev.

**Expected behavior/code**
I would expect to stop and restart the project using docker compose up/down

**Steps to Reproduce**
Spin up a fresh deployment from the main branch, after that use `docker compose down` and right after that `docker compose up` again, this will output the error mentioned above, and the development environment cannot be used as not all services coming up (nginx breaks right after start).

**Environment**
- Impress version: main
- Platform: Linux

**Possible Solution**
```
  app-dev:
    build:
      context: .
      target: backend-development
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    user: ${DOCKER_USER:-1000}
    image: impress:backend-development
    environment:
      - PYLINTHOME=/app/.pylint.d
      - DJANGO_CONFIGURATION=Development
    env_file:
      - env.d/development/common
      - env.d/development/postgresql
    ports:
      - "8071:8000"
    volumes:
      - ./src/backend:/app
      - ./data/static:/data/static
    depends_on:
        - postgresql
        - mailcatcher
        - redis
        - createbuckets
        - nginx # Needs to be removed
```

```
  nginx:
    image: nginx:1.25
    ports:
      - "8083:8083"
    volumes:
      - ./docker/files/etc/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - keycloak
      - app-dev # Needs to be added
```
